//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Operations.CSP.RegSys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Operations.CSP.RegSys.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing an annual Advanced Support for Partners (ASfP) subscription.
        /// </summary>
        public static string Activate_Annual {
            get {
                return ResourceManager.GetString("Activate_Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Advanced Support for Partners Activation Details.
        /// </summary>
        public static string Activate_Banner {
            get {
                return ResourceManager.GetString("Activate_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Operations Team&lt;br/&gt;Microsoft Advanced Support for Partners (ASfP).
        /// </summary>
        public static string Activate_Closing_Signature {
            get {
                return ResourceManager.GetString("Activate_Closing_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive your ASfP invoice by email (at {0}) for the amount of {1} USD approximately 15 days after your ASfP service start date. .
        /// </summary>
        public static string Activate_Email_Invoice {
            get {
                return ResourceManager.GetString("Activate_Email_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will receive your ASfP invoice by email (at {1}) for the amount of {2} USD approximately 15 days after your ASfP service start date. .
        /// </summary>
        public static string Activate_Email_Invoice2 {
            get {
                return ResourceManager.GetString("Activate_Email_Invoice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be advised, standard invoicing dates are on the 15th and 27th of the month.  Your invoicing date is determined by the date we have all required information to process your transaction.  If we have all required information prior to the 14th of the month, the invoicing date will be on the 15th of the month.  Otherwise, it will be the 27th of the month. Please be aware that this date cannot be changed once it is updated in Microsoft’s systems..
        /// </summary>
        public static string Activate_Invoicing_Date {
            get {
                return ResourceManager.GetString("Activate_Invoicing_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many thanks,.
        /// </summary>
        public static string Activate_ManyThanks {
            get {
                return ResourceManager.GetString("Activate_ManyThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the meantime, if you have any questions or urgent cloud support requests please contact your Services Account Manager (SAM) or email &lt;a href=&apos;mailto:svcasfp@microsoft.com&apos;&gt;svcasfp@microsoft.com&lt;/a&gt;..
        /// </summary>
        public static string Activate_MeanTime {
            get {
                return ResourceManager.GetString("Activate_MeanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing a monthly Advanced Support for Partners (ASfP) subscription.
        /// </summary>
        public static string Activate_Monthly {
            get {
                return ResourceManager.GetString("Activate_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ASfP Transition Package will then be active for 12-months..
        /// </summary>
        public static string Activate_PA_Active {
            get {
                return ResourceManager.GetString("Activate_PA_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this package, you gain access to great, new cloud benefits that come with ASfP.  Plus, you will continue to receive the benefits we heard were most valued by you under the Dynamics Partner Advantage plans – including performance-based on-premises support incidents, MPN advisory hours and access to the Microsoft Dynamics training packs..
        /// </summary>
        public static string Activate_PA_Description {
            get {
                return ResourceManager.GetString("Activate_PA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have already started to activate your subscription in our systems and plan to finalize this by the week of {0}. You will receive an email confirming the completed activation from us. Once your subscription is active, {1}, your ASfP Services Account Manager (SAM), will also contact you to schedule a program overview session and share further details..
        /// </summary>
        public static string Activate_PA_SAM_Description {
            get {
                return ResourceManager.GetString("Activate_PA_SAM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing the Advanced Support for Partners (ASfP) PA Transition Package..
        /// </summary>
        public static string Activate_PAIntro_1 {
            get {
                return ResourceManager.GetString("Activate_PAIntro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing the Advanced Support for Partners (ASfP) PA Transition Package and {0}..
        /// </summary>
        public static string Activate_PAIntro_2 {
            get {
                return ResourceManager.GetString("Activate_PAIntro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing the Advanced Support for Partners (ASfP) PA Transition Package, {0}, and {1}..
        /// </summary>
        public static string Activate_PAIntro_3 {
            get {
                return ResourceManager.GetString("Activate_PAIntro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing the Advanced Support for Partners (ASfP) PA Transition Package, {0}, {1}, and {2}..
        /// </summary>
        public static string Activate_PAIntro_4 {
            get {
                return ResourceManager.GetString("Activate_PAIntro_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing the Advanced Support for Partners (ASfP) PA Transition Package, {0}, {1}, {2}, and {3}..
        /// </summary>
        public static string Activate_PAIntro_5 {
            get {
                return ResourceManager.GetString("Activate_PAIntro_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are excited to welcome you as an ASfP Partner and are looking forward to our continued partnership!.
        /// </summary>
        public static string Activate_Partnership {
            get {
                return ResourceManager.GetString("Activate_Partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To help expedite the onboarding process, please send us the following information:.
        /// </summary>
        public static string Activate_PleaseSend {
            get {
                return ResourceManager.GetString("Activate_PleaseSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your subscription is active, one of our ASfP Services Account Managers (SAM) will contact you to schedule a program overview session and share further details..
        /// </summary>
        public static string Activate_PrgmOverview {
            get {
                return ResourceManager.GetString("Activate_PrgmOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name and email details for your preferred billing contact person, if you would like us to send the invoice to someone in your organization other than you..
        /// </summary>
        public static string Activate_SendBillContact {
            get {
                return ResourceManager.GetString("Activate_SendBillContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send us the name and email details for your preferred billing contact person, if you would like us to send the invoice to someone in your organization other than you..
        /// </summary>
        public static string Activate_SendBillContact_Blue {
            get {
                return ResourceManager.GetString("Activate_SendBillContact_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAT ID number you would like us to associate with your order within 3 business days, (by {0}), otherwise VAT will be added to your invoice..
        /// </summary>
        public static string Activate_SendVAT {
            get {
                return ResourceManager.GetString("Activate_SendVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send us the VAT ID number you would like us to associate with your order within 3 business days, (by {0}), otherwise VAT will be added to your invoice..
        /// </summary>
        public static string Activate_SendVAT_Blue {
            get {
                return ResourceManager.GetString("Activate_SendVAT_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have already started to activate ASfP for you in our systems and plan to finalize this by the week of {0}. You will receive an email confirming the completion of your activation..
        /// </summary>
        public static string Activate_StartActivation {
            get {
                return ResourceManager.GetString("Activate_StartActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}..
        /// </summary>
        public static string Activate_Sub_Items_1 {
            get {
                return ResourceManager.GetString("Activate_Sub_Items_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}, and {2}..
        /// </summary>
        public static string Activate_Sub_Items_2 {
            get {
                return ResourceManager.GetString("Activate_Sub_Items_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}, {2}, and {3}..
        /// </summary>
        public static string Activate_Sub_Items_3 {
            get {
                return ResourceManager.GetString("Activate_Sub_Items_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}, {2}, {3}, and {4}..
        /// </summary>
        public static string Activate_Sub_Items_4 {
            get {
                return ResourceManager.GetString("Activate_Sub_Items_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of your Advanced Support for Partners benefits; {0}.
        /// </summary>
        public static string Activate_Subject {
            get {
                return ResourceManager.GetString("Activate_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific.
        /// </summary>
        public static string APGC {
            get {
                return ResourceManager.GetString("APGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Support for Partners Annual Subscription – One-Time Payment – USD 15,000 (local taxes apply).
        /// </summary>
        public static string ASfP_Annual {
            get {
                return ResourceManager.GetString("ASfP_Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W6N-00001 Advanced Support for Partners Annual Subscription – One-Time Payment, 3% discount – USD 14,550 (local taxes apply).
        /// </summary>
        public static string ASfP_Annual_Discount {
            get {
                return ResourceManager.GetString("ASfP_Annual_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W6N-00002 Advanced Support for Partners Annual Subscription in Emerging Markets – One-Time Payment – USD 10,000 (local taxes apply).
        /// </summary>
        public static string ASfP_Emerging {
            get {
                return ResourceManager.GetString("ASfP_Emerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W6M-00001 Advanced Support for Partners Monthly Subscription – Monthly Payment – USD 1,250 (local taxes apply).
        /// </summary>
        public static string ASfP_Monthly {
            get {
                return ResourceManager.GetString("ASfP_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA-13751 ASfP PA Transition Package - One-Time Payment .
        /// </summary>
        public static string ASfP_PA_Transition {
            get {
                return ResourceManager.GetString("ASfP_PA_Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Advanced Support for Partners Confirmation.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W74-00001 1 Cloud Consult Engagement – USD 2,000 (local taxes apply).
        /// </summary>
        public static string Cloud_Consult_1 {
            get {
                return ResourceManager.GetString("Cloud_Consult_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},.
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe, Middle East, Africa.
        /// </summary>
        public static string EMEA {
            get {
                return ResourceManager.GetString("EMEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W67-00001 1-Pack On Premises Support Incident – USD 499 (local taxes apply).
        /// </summary>
        public static string Incident_Pack_1 {
            get {
                return ResourceManager.GetString("Incident_Pack_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W69-00001 5-Pack On Premises Support Incidents – USD 1,999 (local taxes apply).
        /// </summary>
        public static string Incident_Pack_5 {
            get {
                return ResourceManager.GetString("Incident_Pack_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin America.
        /// </summary>
        public static string LATAM {
            get {
                return ResourceManager.GetString("LATAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items were selected.
        /// </summary>
        public static string No_SKU {
            get {
                return ResourceManager.GetString("No_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aka.ms/asfp_privacy.
        /// </summary>
        public static string Privacy_Link {
            get {
                return ResourceManager.GetString("Privacy_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W73-00001 20 Hours of Services Account Management – USD 4,000 (local taxes apply).
        /// </summary>
        public static string SAM_Hours_20 {
            get {
                return ResourceManager.GetString("SAM_Hours_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your continued partnership and support in delivering Microsoft technologies to our mutual customers..
        /// </summary>
        public static string Submit_Closing_ThankYou {
            get {
                return ResourceManager.GetString("Submit_Closing_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Microsoft Advanced Support for Partners team.
        /// </summary>
        public static string Submit_ClosingSignature {
            get {
                return ResourceManager.GetString("Submit_ClosingSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Microsoft representative will be contacting you within 72 hours (Business Hours: Monday to Friday 9am– 5pm Pacific Time Zone) to begin the subscription qualification process.   At that time, we will verify the details of your order and begin processing your request..
        /// </summary>
        public static string Submit_Contact_ASfP {
            get {
                return ResourceManager.GetString("Submit_Contact_ASfP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Microsoft representative will be contacting you within 72 hours (Business Hours: Monday to Friday 9am– 5pm Pacific Time Zone) to begin the subscription qualification process.   At that time, we will verify the details of your order and begin processing your request..
        /// </summary>
        public static string Submit_Contact_PA {
            get {
                return ResourceManager.GetString("Submit_Contact_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the meantime, please feel free to reach out to Advanced Support for Partners at &lt;a href=&apos;mailto:svcasfp@microsoft.com&apos;&gt;svcasfp@microsoft.com&lt;/a&gt; with any questions..
        /// </summary>
        public static string Submit_ContactUs {
            get {
                return ResourceManager.GetString("Submit_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (no prefered location specified).
        /// </summary>
        public static string Submit_NoPreferedLocationSpecified {
            get {
                return ResourceManager.GetString("Submit_NoPreferedLocationSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (no special instructions provided).
        /// </summary>
        public static string Submit_NoSpecialInstructionsProvided {
            get {
                return ResourceManager.GetString("Submit_NoSpecialInstructionsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will find your order details below:.
        /// </summary>
        public static string Submit_OrderDetails {
            get {
                return ResourceManager.GetString("Submit_OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASfP PA Transition Package - One-Time Payment – Promocode: {0}.
        /// </summary>
        public static string Submit_PA_PromoCode {
            get {
                return ResourceManager.GetString("Submit_PA_PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Services Account Manager Location: .
        /// </summary>
        public static string Submit_PreferredSAM_Location {
            get {
                return ResourceManager.GetString("Submit_PreferredSAM_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string Submit_Sincerely {
            get {
                return ResourceManager.GetString("Submit_Sincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions:.
        /// </summary>
        public static string Submit_SpecialInstructions {
            get {
                return ResourceManager.GetString("Submit_SpecialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Advanced Support for Partners (ASfP) Offering Purchase Confirmation.
        /// </summary>
        public static string Submit_Subject {
            get {
                return ResourceManager.GetString("Submit_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting an order request for Microsoft Advanced Support for Partners (ASfP)!.
        /// </summary>
        public static string Submit_ThankYou_ASfP {
            get {
                return ResourceManager.GetString("Submit_ThankYou_ASfP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting an order request for Microsoft Advanced Support for Partners (ASfP) Transition Package!.
        /// </summary>
        public static string Submit_ThankYou_PA {
            get {
                return ResourceManager.GetString("Submit_ThankYou_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aka.ms/asfp_agreement.
        /// </summary>
        public static string TOU_Link {
            get {
                return ResourceManager.GetString("TOU_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.microsoft.com/trademarks/.
        /// </summary>
        public static string TrademarksURL {
            get {
                return ResourceManager.GetString("TrademarksURL", resourceCulture);
            }
        }
    }
}
